[CHANGE] Load and clean facilities data

In [1]:
import pandas as pd

In [3]:
data_path = "/mnt/staas/CLICHE/00_DATA/HSF MASTER FACILITY LIST.xlsx"
fac_df = pd.read_excel(data_path)
fac_df.head(10)

,State,State_code,County,County_code,Payam,Payam_code,Health Facility Name,latitude,longitude,Functional Status
0,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,abiemnom phcc,9.398740,28.823400,Moderately Functional
1,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,awarpiny phcu,9.473620,28.888280,Moderately Functional
2,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,manajoga phcu,9.392128,28.811239,Moderately Functional
3,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,panyang phcu,9.409190,28.912590,Moderately Functional
4,abyei region,SS00,abyei region,SS0001,abyei region,SS000101,abyei civil hospital,9.592052,28.436265,Moderately Functional
5,abyei region,SS00,abyei region,SS0001,abyei region,SS000101,abyei phcc,9.605027,28.432163,Moderately Functional
6,abyei region,SS00,abyei region,SS0001,abyei region,SS000101,agany tok phcu,9.527582,28.434455,Not Functional
7,abyei region,SS00,abyei region,SS0001,abyei region,SS000101,agok phcc,9.357027,28.582675,Not Functional
8,abyei region,SS00,abyei region,SS0001,abyei region,SS000101,amenth bek hospital,9.584825,28.459247,Moderately Functional
9,abyei region,SS00,abyei region,SS0001,abyei region,SS000101,amiet phcu,9.715699,28.465735,Not Functional

In [4]:
fac_df.shape

(1988, 10)

In [5]:
fac_df_clean = fac_df.dropna(subset=['latitude', 'longitude', 'Functional Status'])
fac_df_clean.shape

(1794, 10)

In [6]:
print(fac_df_clean['Functional Status'].unique())

['Moderately Functional' 'Not Functional' 'Highly Functional'
 'Limitedly Functional']

In [6]:
# Select only functional facilities
fac_df_func = fac_df_clean[fac_df_clean['Functional Status'].str.strip().str.lower() != 'not functional']

fac_df_func.shape

(1482, 10)

In [8]:
fac_df_func.head()

,State,State_code,County,County_code,Payam,Payam_code,Health Facility Name,latitude,longitude,Functional Status
0,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,abiemnom phcc,9.398740,28.823400,Moderately Functional
1,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,awarpiny phcu,9.473620,28.888280,Moderately Functional
2,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,manajoga phcu,9.392128,28.811239,Moderately Functional
3,unity,SS06,abiemnhom,SS0601,abiemnhom,SS060101,panyang phcu,9.409190,28.912590,Moderately Functional
4,abyei region,SS00,abyei region,SS0001,abyei region,SS000101,abyei civil hospital,9.592052,28.436265,Moderately Functional

Save coordinates to check in QGIS

In [9]:
coords = fac_df_func[['longitude', 'latitude', 'Health Facility Name', 'Functional Status']] #.astype(float)
coords_csv_path = "/mnt/staas/CLICHE/00_DATA/valid_facilities_coordinates.csv"
coords.to_csv(coords_csv_path, index=False, header=False,float_format='%.6f')